apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orianna-strategy-rest.fullname" . }}-cm
  labels:
    {{- include "orianna-strategy-rest.labels" . | nindent 4}}
data:
  config.yaml: |-
{{- if .Values.config }}
{{ tpl .Values.config . | indent 4 }}
{{- end }}