apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "irent-backend.fullname" . }}-cm
  labels:
    {{- include "irent-backend.labels" . | nindent 4}}
data:
  app.yaml: |-
{{- if .Values.conf }}
{{ tpl .Values.conf . | indent 4 }}
{{- end }}
